package pd.atlas.interfaces;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/interfaces/perks/_atlas.json - do not edit by hand.
 *
 * atlas: interfaces/perks.png
 */
public final class PerksDict {

	private PerksDict() { }

	/** perk_000 */
	public static final IconEntry PERK_000 = new IconEntry("interfaces/perks.png", new int[]{0, 0, 16, 16}, 7322);
	/** perk_001 */
	public static final IconEntry PERK_001 = new IconEntry("interfaces/perks.png", new int[]{16, 0, 16, 16}, 7323);
	/** perk_002 */
	public static final IconEntry PERK_002 = new IconEntry("interfaces/perks.png", new int[]{32, 0, 16, 16}, 7324);
	/** perk_003 */
	public static final IconEntry PERK_003 = new IconEntry("interfaces/perks.png", new int[]{48, 0, 16, 16}, 7325);
	/** perk_004 */
	public static final IconEntry PERK_004 = new IconEntry("interfaces/perks.png", new int[]{64, 0, 16, 16}, 7326);
	/** perk_005 */
	public static final IconEntry PERK_005 = new IconEntry("interfaces/perks.png", new int[]{80, 0, 16, 16}, 7327);
	/** perk_006 */
	public static final IconEntry PERK_006 = new IconEntry("interfaces/perks.png", new int[]{96, 0, 16, 16}, 7328);
	/** perk_007 */
	public static final IconEntry PERK_007 = new IconEntry("interfaces/perks.png", new int[]{112, 0, 16, 16}, 7329);
	/** perk_008 */
	public static final IconEntry PERK_008 = new IconEntry("interfaces/perks.png", new int[]{128, 0, 16, 16}, 7330);
	/** perk_009 */
	public static final IconEntry PERK_009 = new IconEntry("interfaces/perks.png", new int[]{144, 0, 16, 16}, 7331);
	/** perk_010 */
	public static final IconEntry PERK_010 = new IconEntry("interfaces/perks.png", new int[]{160, 0, 16, 16}, 7332);
	/** perk_011 */
	public static final IconEntry PERK_011 = new IconEntry("interfaces/perks.png", new int[]{176, 0, 16, 16}, 7333);
	/** perk_012 */
	public static final IconEntry PERK_012 = new IconEntry("interfaces/perks.png", new int[]{192, 0, 16, 16}, 7334);
	/** perk_013 */
	public static final IconEntry PERK_013 = new IconEntry("interfaces/perks.png", new int[]{208, 0, 16, 16}, 7335);
	/** perk_014 */
	public static final IconEntry PERK_014 = new IconEntry("interfaces/perks.png", new int[]{224, 0, 16, 16}, 7336);
	/** perk_015 */
	public static final IconEntry PERK_015 = new IconEntry("interfaces/perks.png", new int[]{240, 0, 16, 16}, 7337);
	/** perk_016 */
	public static final IconEntry PERK_016 = new IconEntry("interfaces/perks.png", new int[]{0, 16, 16, 16}, 7338);
	/** perk_017 */
	public static final IconEntry PERK_017 = new IconEntry("interfaces/perks.png", new int[]{16, 16, 16, 16}, 7339);
	/** perk_018 */
	public static final IconEntry PERK_018 = new IconEntry("interfaces/perks.png", new int[]{32, 16, 16, 16}, 7340);
	/** perk_019 */
	public static final IconEntry PERK_019 = new IconEntry("interfaces/perks.png", new int[]{48, 16, 16, 16}, 7341);
	/** perk_020 */
	public static final IconEntry PERK_020 = new IconEntry("interfaces/perks.png", new int[]{64, 16, 16, 16}, 7342);
	/** perk_021 */
	public static final IconEntry PERK_021 = new IconEntry("interfaces/perks.png", new int[]{80, 16, 16, 16}, 7343);
	/** perk_022 */
	public static final IconEntry PERK_022 = new IconEntry("interfaces/perks.png", new int[]{96, 16, 16, 16}, 7344);
	/** perk_023 */
	public static final IconEntry PERK_023 = new IconEntry("interfaces/perks.png", new int[]{112, 16, 16, 16}, 7345);
	/** perk_024 */
	public static final IconEntry PERK_024 = new IconEntry("interfaces/perks.png", new int[]{128, 16, 16, 16}, 7346);
	/** perk_025 */
	public static final IconEntry PERK_025 = new IconEntry("interfaces/perks.png", new int[]{144, 16, 16, 16}, 7347);
	/** perk_026 */
	public static final IconEntry PERK_026 = new IconEntry("interfaces/perks.png", new int[]{160, 16, 16, 16}, 7348);
	/** perk_027 */
	public static final IconEntry PERK_027 = new IconEntry("interfaces/perks.png", new int[]{176, 16, 16, 16}, 7349);
	/** perk_028 */
	public static final IconEntry PERK_028 = new IconEntry("interfaces/perks.png", new int[]{192, 16, 16, 16}, 7350);
	/** perk_029 */
	public static final IconEntry PERK_029 = new IconEntry("interfaces/perks.png", new int[]{208, 16, 16, 16}, 7351);
	/** perk_030 */
	public static final IconEntry PERK_030 = new IconEntry("interfaces/perks.png", new int[]{224, 16, 16, 16}, 7352);
	/** perk_031 */
	public static final IconEntry PERK_031 = new IconEntry("interfaces/perks.png", new int[]{240, 16, 16, 16}, 7353);
	/** perk_032 */
	public static final IconEntry PERK_032 = new IconEntry("interfaces/perks.png", new int[]{0, 32, 16, 16}, 7354);
	/** perk_033 */
	public static final IconEntry PERK_033 = new IconEntry("interfaces/perks.png", new int[]{16, 32, 16, 16}, 7355);
	/** perk_034 */
	public static final IconEntry PERK_034 = new IconEntry("interfaces/perks.png", new int[]{32, 32, 16, 16}, 7356);
	/** perk_035 */
	public static final IconEntry PERK_035 = new IconEntry("interfaces/perks.png", new int[]{48, 32, 16, 16}, 7357);
	/** perk_036 */
	public static final IconEntry PERK_036 = new IconEntry("interfaces/perks.png", new int[]{64, 32, 16, 16}, 7358);
	/** perk_037 */
	public static final IconEntry PERK_037 = new IconEntry("interfaces/perks.png", new int[]{80, 32, 16, 16}, 7359);
	/** perk_038 */
	public static final IconEntry PERK_038 = new IconEntry("interfaces/perks.png", new int[]{96, 32, 16, 16}, 7360);
	/** perk_039 */
	public static final IconEntry PERK_039 = new IconEntry("interfaces/perks.png", new int[]{112, 32, 16, 16}, 7361);
	/** perk_040 */
	public static final IconEntry PERK_040 = new IconEntry("interfaces/perks.png", new int[]{128, 32, 16, 16}, 7362);
	/** perk_041 */
	public static final IconEntry PERK_041 = new IconEntry("interfaces/perks.png", new int[]{144, 32, 16, 16}, 7363);
	/** perk_042 */
	public static final IconEntry PERK_042 = new IconEntry("interfaces/perks.png", new int[]{160, 32, 16, 16}, 7364);
	/** perk_043 */
	public static final IconEntry PERK_043 = new IconEntry("interfaces/perks.png", new int[]{176, 32, 16, 16}, 7365);
	/** perk_044 */
	public static final IconEntry PERK_044 = new IconEntry("interfaces/perks.png", new int[]{192, 32, 16, 16}, 7366);
	/** perk_045 */
	public static final IconEntry PERK_045 = new IconEntry("interfaces/perks.png", new int[]{208, 32, 16, 16}, 7367);
	/** perk_046 */
	public static final IconEntry PERK_046 = new IconEntry("interfaces/perks.png", new int[]{224, 32, 16, 16}, 7368);
	/** perk_047 */
	public static final IconEntry PERK_047 = new IconEntry("interfaces/perks.png", new int[]{240, 32, 16, 16}, 7369);
	/** perk_048 */
	public static final IconEntry PERK_048 = new IconEntry("interfaces/perks.png", new int[]{0, 48, 16, 16}, 7370);
	/** perk_049 */
	public static final IconEntry PERK_049 = new IconEntry("interfaces/perks.png", new int[]{16, 48, 16, 16}, 7371);
	/** perk_050 */
	public static final IconEntry PERK_050 = new IconEntry("interfaces/perks.png", new int[]{32, 48, 16, 16}, 7372);
	/** perk_051 */
	public static final IconEntry PERK_051 = new IconEntry("interfaces/perks.png", new int[]{48, 48, 16, 16}, 7373);
	/** perk_052 */
	public static final IconEntry PERK_052 = new IconEntry("interfaces/perks.png", new int[]{64, 48, 16, 16}, 7374);
	/** perk_053 */
	public static final IconEntry PERK_053 = new IconEntry("interfaces/perks.png", new int[]{80, 48, 16, 16}, 7375);
	/** perk_054 */
	public static final IconEntry PERK_054 = new IconEntry("interfaces/perks.png", new int[]{96, 48, 16, 16}, 7376);
	/** perk_055 */
	public static final IconEntry PERK_055 = new IconEntry("interfaces/perks.png", new int[]{112, 48, 16, 16}, 7377);
	/** perk_056 */
	public static final IconEntry PERK_056 = new IconEntry("interfaces/perks.png", new int[]{128, 48, 16, 16}, 7378);
	/** perk_057 */
	public static final IconEntry PERK_057 = new IconEntry("interfaces/perks.png", new int[]{144, 48, 16, 16}, 7379);
	/** perk_058 */
	public static final IconEntry PERK_058 = new IconEntry("interfaces/perks.png", new int[]{160, 48, 16, 16}, 7380);
	/** perk_059 */
	public static final IconEntry PERK_059 = new IconEntry("interfaces/perks.png", new int[]{176, 48, 16, 16}, 7381);
	/** perk_060 */
	public static final IconEntry PERK_060 = new IconEntry("interfaces/perks.png", new int[]{192, 48, 16, 16}, 7382);
	/** perk_061 */
	public static final IconEntry PERK_061 = new IconEntry("interfaces/perks.png", new int[]{208, 48, 16, 16}, 7383);
	/** perk_062 */
	public static final IconEntry PERK_062 = new IconEntry("interfaces/perks.png", new int[]{224, 48, 16, 16}, 7384);
	/** perk_063 */
	public static final IconEntry PERK_063 = new IconEntry("interfaces/perks.png", new int[]{240, 48, 16, 16}, 7385);
	/** perk_064 */
	public static final IconEntry PERK_064 = new IconEntry("interfaces/perks.png", new int[]{0, 64, 16, 16}, 7386);
	/** perk_065 */
	public static final IconEntry PERK_065 = new IconEntry("interfaces/perks.png", new int[]{16, 64, 16, 16}, 7387);
	/** perk_066 */
	public static final IconEntry PERK_066 = new IconEntry("interfaces/perks.png", new int[]{32, 64, 16, 16}, 7388);
	/** perk_067 */
	public static final IconEntry PERK_067 = new IconEntry("interfaces/perks.png", new int[]{48, 64, 16, 16}, 7389);
	/** perk_068 */
	public static final IconEntry PERK_068 = new IconEntry("interfaces/perks.png", new int[]{64, 64, 16, 16}, 7390);
	/** perk_069 */
	public static final IconEntry PERK_069 = new IconEntry("interfaces/perks.png", new int[]{80, 64, 16, 16}, 7391);
	/** perk_070 */
	public static final IconEntry PERK_070 = new IconEntry("interfaces/perks.png", new int[]{96, 64, 16, 16}, 7392);
	/** perk_071 */
	public static final IconEntry PERK_071 = new IconEntry("interfaces/perks.png", new int[]{112, 64, 16, 16}, 7393);
	/** perk_072 */
	public static final IconEntry PERK_072 = new IconEntry("interfaces/perks.png", new int[]{128, 64, 16, 16}, 7394);
	/** perk_073 */
	public static final IconEntry PERK_073 = new IconEntry("interfaces/perks.png", new int[]{144, 64, 16, 16}, 7395);
	/** perk_074 */
	public static final IconEntry PERK_074 = new IconEntry("interfaces/perks.png", new int[]{160, 64, 16, 16}, 7396);
	/** perk_075 */
	public static final IconEntry PERK_075 = new IconEntry("interfaces/perks.png", new int[]{176, 64, 16, 16}, 7397);
	/** perk_076 */
	public static final IconEntry PERK_076 = new IconEntry("interfaces/perks.png", new int[]{192, 64, 16, 16}, 7398);
	/** perk_077 */
	public static final IconEntry PERK_077 = new IconEntry("interfaces/perks.png", new int[]{208, 64, 16, 16}, 7399);
	/** perk_078 */
	public static final IconEntry PERK_078 = new IconEntry("interfaces/perks.png", new int[]{224, 64, 16, 16}, 7400);
	/** perk_079 */
	public static final IconEntry PERK_079 = new IconEntry("interfaces/perks.png", new int[]{240, 64, 16, 16}, 7401);
	/** perk_080 */
	public static final IconEntry PERK_080 = new IconEntry("interfaces/perks.png", new int[]{0, 80, 16, 16}, 7402);
	/** perk_081 */
	public static final IconEntry PERK_081 = new IconEntry("interfaces/perks.png", new int[]{16, 80, 16, 16}, 7403);
	/** perk_082 */
	public static final IconEntry PERK_082 = new IconEntry("interfaces/perks.png", new int[]{32, 80, 16, 16}, 7404);
	/** perk_083 */
	public static final IconEntry PERK_083 = new IconEntry("interfaces/perks.png", new int[]{48, 80, 16, 16}, 7405);
	/** perk_084 */
	public static final IconEntry PERK_084 = new IconEntry("interfaces/perks.png", new int[]{64, 80, 16, 16}, 7406);
	/** perk_085 */
	public static final IconEntry PERK_085 = new IconEntry("interfaces/perks.png", new int[]{80, 80, 16, 16}, 7407);
	/** perk_086 */
	public static final IconEntry PERK_086 = new IconEntry("interfaces/perks.png", new int[]{96, 80, 16, 16}, 7408);
	/** perk_087 */
	public static final IconEntry PERK_087 = new IconEntry("interfaces/perks.png", new int[]{112, 80, 16, 16}, 7409);
	/** perk_088 */
	public static final IconEntry PERK_088 = new IconEntry("interfaces/perks.png", new int[]{128, 80, 16, 16}, 7410);
	/** perk_089 */
	public static final IconEntry PERK_089 = new IconEntry("interfaces/perks.png", new int[]{144, 80, 16, 16}, 7411);
	/** perk_090 */
	public static final IconEntry PERK_090 = new IconEntry("interfaces/perks.png", new int[]{160, 80, 16, 16}, 7412);
	/** perk_091 */
	public static final IconEntry PERK_091 = new IconEntry("interfaces/perks.png", new int[]{176, 80, 16, 16}, 7413);
	/** perk_092 */
	public static final IconEntry PERK_092 = new IconEntry("interfaces/perks.png", new int[]{192, 80, 16, 16}, 7414);
	/** perk_093 */
	public static final IconEntry PERK_093 = new IconEntry("interfaces/perks.png", new int[]{208, 80, 16, 16}, 7415);
	/** perk_094 */
	public static final IconEntry PERK_094 = new IconEntry("interfaces/perks.png", new int[]{224, 80, 16, 16}, 7416);
	/** perk_095 */
	public static final IconEntry PERK_095 = new IconEntry("interfaces/perks.png", new int[]{240, 80, 16, 16}, 7417);
	/** perk_096 */
	public static final IconEntry PERK_096 = new IconEntry("interfaces/perks.png", new int[]{0, 96, 16, 16}, 7418);
	/** perk_097 */
	public static final IconEntry PERK_097 = new IconEntry("interfaces/perks.png", new int[]{16, 96, 16, 16}, 7419);
	/** perk_098 */
	public static final IconEntry PERK_098 = new IconEntry("interfaces/perks.png", new int[]{32, 96, 16, 16}, 7420);
	/** perk_099 */
	public static final IconEntry PERK_099 = new IconEntry("interfaces/perks.png", new int[]{48, 96, 16, 16}, 7421);
	/** perk_100 */
	public static final IconEntry PERK_100 = new IconEntry("interfaces/perks.png", new int[]{64, 96, 16, 16}, 7422);
	/** perk_101 */
	public static final IconEntry PERK_101 = new IconEntry("interfaces/perks.png", new int[]{80, 96, 16, 16}, 7423);
	/** perk_102 */
	public static final IconEntry PERK_102 = new IconEntry("interfaces/perks.png", new int[]{96, 96, 16, 16}, 7424);
	/** perk_103 */
	public static final IconEntry PERK_103 = new IconEntry("interfaces/perks.png", new int[]{112, 96, 16, 16}, 7425);
	/** perk_104 */
	public static final IconEntry PERK_104 = new IconEntry("interfaces/perks.png", new int[]{128, 96, 16, 16}, 7426);
	/** perk_105 */
	public static final IconEntry PERK_105 = new IconEntry("interfaces/perks.png", new int[]{144, 96, 16, 16}, 7427);
	/** perk_106 */
	public static final IconEntry PERK_106 = new IconEntry("interfaces/perks.png", new int[]{160, 96, 16, 16}, 7428);
	/** perk_107 */
	public static final IconEntry PERK_107 = new IconEntry("interfaces/perks.png", new int[]{176, 96, 16, 16}, 7429);
	/** perk_108 */
	public static final IconEntry PERK_108 = new IconEntry("interfaces/perks.png", new int[]{192, 96, 16, 16}, 7430);
	/** perk_109 */
	public static final IconEntry PERK_109 = new IconEntry("interfaces/perks.png", new int[]{208, 96, 16, 16}, 7431);
	/** perk_110 */
	public static final IconEntry PERK_110 = new IconEntry("interfaces/perks.png", new int[]{224, 96, 16, 16}, 7432);
	/** perk_111 */
	public static final IconEntry PERK_111 = new IconEntry("interfaces/perks.png", new int[]{240, 96, 16, 16}, 7433);
	/** perk_112 */
	public static final IconEntry PERK_112 = new IconEntry("interfaces/perks.png", new int[]{0, 112, 16, 16}, 7434);
	/** perk_113 */
	public static final IconEntry PERK_113 = new IconEntry("interfaces/perks.png", new int[]{16, 112, 16, 16}, 7435);
	/** perk_114 */
	public static final IconEntry PERK_114 = new IconEntry("interfaces/perks.png", new int[]{32, 112, 16, 16}, 7436);
	/** perk_115 */
	public static final IconEntry PERK_115 = new IconEntry("interfaces/perks.png", new int[]{48, 112, 16, 16}, 7437);
	/** perk_116 */
	public static final IconEntry PERK_116 = new IconEntry("interfaces/perks.png", new int[]{64, 112, 16, 16}, 7438);
	/** perk_117 */
	public static final IconEntry PERK_117 = new IconEntry("interfaces/perks.png", new int[]{80, 112, 16, 16}, 7439);
	/** perk_118 */
	public static final IconEntry PERK_118 = new IconEntry("interfaces/perks.png", new int[]{96, 112, 16, 16}, 7440);
	/** perk_119 */
	public static final IconEntry PERK_119 = new IconEntry("interfaces/perks.png", new int[]{112, 112, 16, 16}, 7441);
	/** perk_120 */
	public static final IconEntry PERK_120 = new IconEntry("interfaces/perks.png", new int[]{128, 112, 16, 16}, 7442);
	/** perk_121 */
	public static final IconEntry PERK_121 = new IconEntry("interfaces/perks.png", new int[]{144, 112, 16, 16}, 7443);
	/** perk_122 */
	public static final IconEntry PERK_122 = new IconEntry("interfaces/perks.png", new int[]{160, 112, 16, 16}, 7444);
	/** perk_123 */
	public static final IconEntry PERK_123 = new IconEntry("interfaces/perks.png", new int[]{176, 112, 16, 16}, 7445);
	/** perk_124 */
	public static final IconEntry PERK_124 = new IconEntry("interfaces/perks.png", new int[]{192, 112, 16, 16}, 7446);
	/** perk_125 */
	public static final IconEntry PERK_125 = new IconEntry("interfaces/perks.png", new int[]{208, 112, 16, 16}, 7447);
	/** perk_126 */
	public static final IconEntry PERK_126 = new IconEntry("interfaces/perks.png", new int[]{224, 112, 16, 16}, 7448);
	/** perk_127 */
	public static final IconEntry PERK_127 = new IconEntry("interfaces/perks.png", new int[]{240, 112, 16, 16}, 7449);
}
