package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/consum/scroll_amulet/scroll_empty/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/consum/scroll_amulet/scroll_empty.png
 */
public final class ConsumScrollAmuletScrollEmptyDict {

	private ConsumScrollAmuletScrollEmptyDict() { }

	/** SCROLL_EMPTY */
	public static final IconEntry SCROLL_EMPTY_C1_R1 = new IconEntry("sprites/items/consum/scroll_amulet/scroll_empty.png", new int[]{1, 1, 15, 14}, 7134);
	/** semantic alias for SCROLL_EMPTY_C1_R1 */
	public static final IconEntry SCROLL_EMPTY = SCROLL_EMPTY_C1_R1;
}
