package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/equipment/wand/unique_wand/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/equipment/wand/unique_wand.png
 */
public final class EquipmentWandUniqueWandDict {

	private EquipmentWandUniqueWandDict() { }

	/** LEGACY_CANNON_OF_MAGE */
	public static final IconEntry LEGACY_CANNON_OF_MAGE = new IconEntry("sprites/items/equipment/wand/unique_wand.png", new int[]{0, 1, 15, 15}, 7081);
	/** UNIQUE_WAND_EXTRA_1 - 黑色法杖 */
	public static final IconEntry UNIQUE_WAND_EXTRA_1 = new IconEntry("sprites/items/equipment/wand/unique_wand.png", new int[]{16, 0, 16, 16}, 7505);
}
