package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/ground/grounding_items/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/ground/grounding_items.png
 */
public final class GroundGroundingItemsDict {

	private GroundGroundingItemsDict() { }

	/** NORMAL_REMAINS */
	public static final IconEntry GROUNDING_ITEMS_C1_R1 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{0, 1, 15, 14}, 7093);
	/** semantic alias for GROUNDING_ITEMS_C1_R1 */
	public static final IconEntry NORMAL_REMAINS = GROUNDING_ITEMS_C1_R1;
	/** HERO_BONES */
	public static final IconEntry GROUNDING_ITEMS_C2_R1 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{16, 1, 15, 14}, 7094);
	/** semantic alias for GROUNDING_ITEMS_C2_R1 */
	public static final IconEntry HERO_BONES = GROUNDING_ITEMS_C2_R1;
	/** CHEST#0 */
	public static final IconEntry GROUNDING_ITEMS_C4_R1 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{48, 1, 16, 15}, 7095);
	/** semantic alias for GROUNDING_ITEMS_C4_R1 */
	public static final IconEntry CHEST_0 = GROUNDING_ITEMS_C4_R1;
	/** LOCKED_CHEST#0 */
	public static final IconEntry GROUNDING_ITEMS_C5_R1 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{64, 1, 16, 15}, 7096);
	/** semantic alias for GROUNDING_ITEMS_C5_R1 */
	public static final IconEntry LOCKED_CHEST_0 = GROUNDING_ITEMS_C5_R1;
	/** CRYSTAL_CHEST#0 */
	public static final IconEntry GROUNDING_ITEMS_C6_R1 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{80, 1, 16, 15}, 7097);
	/** semantic alias for GROUNDING_ITEMS_C6_R1 */
	public static final IconEntry CRYSTAL_CHEST_0 = GROUNDING_ITEMS_C6_R1;
	/** EBONY_CHEST#0 */
	public static final IconEntry GROUNDING_ITEMS_C10_R1 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{144, 1, 16, 14}, 7098);
	/** semantic alias for GROUNDING_ITEMS_C10_R1 */
	public static final IconEntry EBONY_CHEST_0 = GROUNDING_ITEMS_C10_R1;
	/** NORMAL_GRAVESTONE */
	public static final IconEntry GROUNDING_ITEMS_C1_R2 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{1, 16, 14, 15}, 7099);
	/** semantic alias for GROUNDING_ITEMS_C1_R2 */
	public static final IconEntry NORMAL_GRAVESTONE = GROUNDING_ITEMS_C1_R2;
	/** MARBLE_GRAVESTONE */
	public static final IconEntry GROUNDING_ITEMS_C2_R2 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{17, 16, 14, 15}, 7100);
	/** semantic alias for GROUNDING_ITEMS_C2_R2 */
	public static final IconEntry MARBLE_GRAVESTONE = GROUNDING_ITEMS_C2_R2;
	/** TREASURE_SPOT */
	public static final IconEntry GROUNDING_ITEMS_C1_R3 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{1, 33, 14, 15}, 7101);
	/** semantic alias for GROUNDING_ITEMS_C1_R3 */
	public static final IconEntry TREASURE_SPOT = GROUNDING_ITEMS_C1_R3;
	/** TREASURE_SPOT_2 */
	public static final IconEntry GROUNDING_ITEMS_C2_R3 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{17, 33, 14, 15}, 7102);
	/** semantic alias for GROUNDING_ITEMS_C2_R3 */
	public static final IconEntry TREASURE_SPOT_2 = GROUNDING_ITEMS_C2_R3;
	/** FLOWER_POT */
	public static final IconEntry GROUNDING_ITEMS_C3_R4 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{33, 48, 14, 15}, 7103);
	/** semantic alias for GROUNDING_ITEMS_C3_R4 */
	public static final IconEntry FLOWER_POT = GROUNDING_ITEMS_C3_R4;
	/** ALCHEMY_CAULDRON */
	public static final IconEntry GROUNDING_ITEMS_C4_R4 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{48, 48, 16, 15}, 7104);
	/** semantic alias for GROUNDING_ITEMS_C4_R4 */
	public static final IconEntry ALCHEMY_CAULDRON = GROUNDING_ITEMS_C4_R4;
	/** ANVIL */
	public static final IconEntry GROUNDING_ITEMS_C5_R4 = new IconEntry("sprites/items/ground/grounding_items.png", new int[]{64, 49, 16, 14}, 7105);
	/** semantic alias for GROUNDING_ITEMS_C5_R4 */
	public static final IconEntry ANVIL = GROUNDING_ITEMS_C5_R4;
}
