package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/ground/waypoint/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/ground/waypoint.png
 */
public final class GroundWaypointDict {

	private GroundWaypointDict() { }

	/** WAYPOINT */
	public static final IconEntry WAYPOINT_C1_R1 = new IconEntry("sprites/items/ground/waypoint.png", new int[]{0, 0, 16, 16}, 7135);
	/** semantic alias for WAYPOINT_C1_R1 */
	public static final IconEntry WAYPOINT = WAYPOINT_C1_R1;
	/** WAYPOINT_END */
	public static final IconEntry WAYPOINT_C1_R2 = new IconEntry("sprites/items/ground/waypoint.png", new int[]{0, 16, 16, 16}, 7136);
	/** semantic alias for WAYPOINT_C1_R2 */
	public static final IconEntry WAYPOINT_END = WAYPOINT_C1_R2;
}
