package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/specific/currency/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/specific/currency.png
 */
public final class SpecificCurrencyDict {

	private SpecificCurrencyDict() { }

	/** GOLD#0 */
	public static final IconEntry CURRENCY_C1_R1 = new IconEntry("sprites/items/specific/currency.png", new int[]{0, 0, 15, 13}, 7107);
	/** semantic alias for CURRENCY_C1_R1 */
	public static final IconEntry GOLD_0 = CURRENCY_C1_R1;
	/** ENERGY#0 */
	public static final IconEntry CURRENCY_C2_R1 = new IconEntry("sprites/items/specific/currency.png", new int[]{16, 0, 16, 16}, 7108);
	/** semantic alias for CURRENCY_C2_R1 */
	public static final IconEntry ENERGY_0 = CURRENCY_C2_R1;
	/** GOLD#1 - 小额金币（单枚），地面金币堆 <75 时使用 */
	public static final IconEntry CURRENCY_C3_R1 = new IconEntry("sprites/items/specific/currency.png", new int[]{35, 3, 9, 10}, 7510);
	/** semantic alias for CURRENCY_C3_R1 */
	public static final IconEntry GOLD_1 = CURRENCY_C3_R1;
}
