package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/specific/place_holde_fruit/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/specific/place_holde_fruit.png
 */
public final class SpecificPlaceHoldeFruitDict {

	private SpecificPlaceHoldeFruitDict() { }

	/** FRUIT_HOLDER#0 */
	public static final IconEntry FRUIT_HOLDER_0 = new IconEntry("sprites/items/specific/place_holde_fruit.png", new int[]{5, 4, 7, 9}, 7194);
	/** LARGE_FRUIT_HOLDER#0 */
	public static final IconEntry LARGE_FRUIT_HOLDER_0 = new IconEntry("sprites/items/specific/place_holde_fruit.png", new int[]{18, 1, 13, 14}, 7195);
}
