package pd.atlas.items;

import pd.atlas.IconEntry;

/**
 * Icon dictionary generated by tools/gen-atlas-dict.ps1 from
 * tools/atlas-meta/items/specific/key/_atlas.json - do not edit by hand.
 *
 * atlas: sprites/items/specific/key.png
 */
public final class SpecificKeyDict {

	private SpecificKeyDict() { }

	/** IRON_KEY */
	public static final IconEntry KEY_C1_R1 = new IconEntry("sprites/items/specific/key.png", new int[]{4, 1, 8, 14}, 7109);
	/** semantic alias for KEY_C1_R1 */
	public static final IconEntry IRON_KEY = KEY_C1_R1;
	/** GOLDEN_KEY */
	public static final IconEntry KEY_C2_R1 = new IconEntry("sprites/items/specific/key.png", new int[]{20, 1, 8, 14}, 7110);
	/** semantic alias for KEY_C2_R1 */
	public static final IconEntry GOLDEN_KEY = KEY_C2_R1;
	/** WORN_KEY */
	public static final IconEntry KEY_C3_R1 = new IconEntry("sprites/items/specific/key.png", new int[]{36, 1, 8, 14}, 7111);
	/** semantic alias for KEY_C3_R1 */
	public static final IconEntry WORN_KEY = KEY_C3_R1;
	/** CRYSTAL_KEY */
	public static final IconEntry KEY_C4_R1 = new IconEntry("sprites/items/specific/key.png", new int[]{52, 1, 8, 14}, 7112);
	/** semantic alias for KEY_C4_R1 */
	public static final IconEntry CRYSTAL_KEY = KEY_C4_R1;
}
